//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QLThuVienEntities5 : DbContext
    {
        public QLThuVienEntities5()
            : base("name=QLThuVienEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answers { get; set; }
        public DbSet<phieumuon> phieumuons { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Sach> Saches { get; set; }
        public DbSet<tbl_DocGia> tbl_DocGia { get; set; }
        public DbSet<tbl_DocGia_Tam> tbl_DocGia_Tam { get; set; }
        public DbSet<tbl_LoaiNV> tbl_LoaiNV { get; set; }
        public DbSet<tbl_NhanVien> tbl_NhanVien { get; set; }
    
        public virtual int sp_Giahan(Nullable<int> idsach)
        {
            var idsachParameter = idsach.HasValue ?
                new ObjectParameter("idsach", idsach) :
                new ObjectParameter("idsach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Giahan", idsachParameter);
        }
    }
}
