//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieumuon
    {
        public string IDdocgia { get; set; }
        public int IDsach { get; set; }
        public System.DateTime Ngaymuon { get; set; }
        public Nullable<System.DateTime> Ngayhethan { get; set; }
        public Nullable<System.DateTime> Ngaytra { get; set; }
        public Nullable<int> SolanGH { get; set; }
        public string Ghichu { get; set; }
    
        public virtual tbl_DocGia tbl_DocGia { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
