//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.phieumuons = new HashSet<phieumuon>();
        }
    
        public int ID { get; set; }
        public string Tensach { get; set; }
        public string Theloai { get; set; }
        public string Tacgia { get; set; }
        public string NXB { get; set; }
        public Nullable<int> Namsx { get; set; }
    
        public virtual ICollection<phieumuon> phieumuons { get; set; }
    }
}
